### ISSUE TITLE
CDCTL-H3 Quartus FPGA Programming Failure

### ISSUE THREAD

**Issue by Logicdesign312** [dukelec/cdpga#1]
I bought two pieces of this board and tried to program a design that works on other 10M02 Intel Parts. 
Wired the board to download .pof file through the JTAG port. I verified that power supplies are working and JTAG ports
are wired correctly.  When I try to program the part, I always get the same error which is that the progress bar always fails at 4%
into the programming cycle. This is true whether I am programing the part of just verifying that it is erased. The only thing I can
do completely is erasing the part.  I verified that the JTAG chain is working. Both boards I bought, behave exactly the same way. 

Could anyone help me or direct me to the correct place to look into this problem?  I am suspecting that the actual 10M02DCV36
FPGA's on both boards are defective and when trying to program the User Flash Memory on board, there is a defective addressing memory area where the programmer fails. 

Thank You in advance for your help.

**Comment by dukelec** [comment]
What is the scheme of usb blaster you are using?
Does it use mcu for the core or ft245 + cpld ?

How are you wired? Can you provide photos?
Can the sof file be downloaded and run successfully?
Can you provide a screenshot of the programmer GUI window?

**Comment by Logicdesign312** [comment]
Thank You for your response.

 

Attached is the JTAG wiring on the board. I am using a Terasic USB blaster which I have been using for years and works on everything else. 

Also a picture of the actual board wiring and the error message when programming with the Altera Quartus programmer.

 

I am not sure what you mean by mcu from the core or ft245 + cpld.

 

I don’t have and sof file, only the pof file generated by the Quartus version 21.

 

This design and programming works fine when using a 10M02SC169 Core Board from QM-Tech.

 

Thank You,

 

Logicdesign312

**Comment by dukelec** [comment]
I can't see your images.

By default it should output sof files, I don't know how your project is configured.

Try my packaged project and try to burn the sof and pof files directly first:
(Beware that all IO ports will be open-drain output.)

[cdpga-h3-test-full.zip](https://github.com/dukelec/cdpga/files/8495484/cdpga-h3-test-full.zip)

**Comment by Logicdesign312** [comment]
I tried your Test project above and get exactly the same results. I can program the .sof file but, when I try the .pof, I get the same error as in my design, which is 4% into the programming, it fails. This tells me that the CFM can't be programmed.  This doesn't do me much good because I need to program the flash for non-volatility.  No problem with the I/O's since I don't have anything connected to them. Attached are the screenshots showing the error and the board wiring. 
![Capture  pof Test Programming](https://user-images.githubusercontent.com/102680824/163579051-a633d81f-26be-45d5-857f-05df413edba6.JPG)

**Comment by Logicdesign312** [comment]
Not sure if you got all three attachments so, here are other two. 
![Capture  sof Test Programming](https://user-images.githubusercontent.com/102680824/163579903-5daff1b6-99bc-49a2-b20b-39a4bf7aa856.JPG)
![Dukeelec wiring picture](https://user-images.githubusercontent.com/102680824/163579974-3b560fa4-3f09-468d-b75f-020a1c69677b.jpg)

**Comment by Logicdesign312** [comment]
Hi dukelec, I got it working now!  I was using Quartus Version 21 to develop my project and program the device. Also, to program your test file. I changed to an earlier version of Quartus (18) and it all worked. I can now program the CFM and everything else.
You can close this case.  Thank You.    Logicdesign312

**Comment by Logicdesign312** [comment]
Hi dukelec, I got it working now! I was using Quartus Version 21 to develop my project and program the device. Also, to program your test file. I changed to an earlier version of Quartus (18) and it all worked. I can now program the CFM and everything else.
You can close this case. Thank You. Logicdesign312
